Repository InnoSWP/syntax-visualizer, pull requests merged in 2022-06, with the labels that each got.

#28 Readme added
  README.md
  assets/tree.png
Labels: documentation

#29 fix editor height, refactor scss vars to css native ones
  src/App.vue
  src/assets/base.css
  src/assets/variables.css
  src/components/AppTab.vue
  src/components/CodeEditor.vue
  src/components/CodeEditorMonaco.vue
  src/components/TheTabs.vue
  src/components/header/TheHeader.vue
Labels: bug, editor

#33 Implement AST graph representation
  .eslintrc.cjs
  src/components/AbstractSyntaxTree.vue
  src/components/AbstractSyntaxTreeGraph.vue
  src/components/AbstractSyntaxTreeJson.vue
  src/components/AppTab.vue
  src/components/TheTabs.vue
  src/components/tree-graph/TreeGraph.vue
  src/components/tree-graph/TreeGraphNode.vue
  src/components/tree-graph/domGraphicUtils.ts
  src/components/tree-graph/tmpProxy.ts
  src/components/tree-graph/types.ts
  src/core/languages/javascript/parsers/babel.ts
  src/core/types.ts
  src/stores/settings.ts
Labels: ast

#36 Split CI/CD workflow into QA and CD
  .github/workflows/cd.yml
  .github/workflows/ci-cd.yml
  .github/workflows/qa.yml
Labels: ci/cd

#40 NCM representation implemented
  src/components/NodeCoordinatesMatrix.vue
  src/components/TheTabs.vue
Labels: ncm

#46 Add AppIcon component with icons from design
  src/components/AppIcon.vue
  src/components/icons/CopiedIcon.vue
  src/components/icons/CopyIcon.vue
  src/components/icons/DownloadAstNcmIcon.vue
  src/components/icons/DownloadCodeIcon.vue
  src/components/icons/FileCodeIcon.vue
  src/components/icons/GearIcon.vue
  src/components/icons/InfoIcon.vue
  src/components/icons/MatrixIcon.vue
  src/components/icons/MoonIcon.vue
  src/components/icons/PythonIcon.vue
  src/components/icons/ShareIcon.vue
  src/components/icons/SunIcon.vue
  src/components/icons/TreeIcon.vue
  src/components/icons/index.ts
  src/router/index.ts
Labels: 💅appearance

#48 Run QA on dev too but without E2E tests
  .github/workflows/qa.yml
Labels: ci/cd

#51 Minor UI improvements (header, tabs)
  src/components/AppTab.vue
  src/components/TheHeader.vue
  src/components/TheTabs.vue
Labels: 💅appearance

#59 Monaco-editor replaced with Codemirror
  package-lock.json
  package.json
  src/components/TheTabs.vue
  src/components/editor/CodeEditor.vue
  src/components/editor/codemirror/CodeEditorCodemirror.vue
  src/components/editor/codemirror/extensions/defaultExtensions.ts
  src/components/editor/codemirror/extensions/index.ts
  src/components/editor/codemirror/extensions/updateListeners.ts
  src/components/editor/codemirror/loadLanguageSupport.ts
  src/components/editor/monaco/CodeEditorMonaco.vue
  src/components/editor/monaco/themes.ts
  src/core/languages/javascript/index.ts
  src/core/types.ts
  src/stores/settings.ts
  vite.config.ts
Labels: editor

#60 ci-cd: setup SonarCloud and coverage
  .github/workflows/test.yml
  cypress.config.ts
  cypress/support/e2e.ts
  env.d.ts
  package-lock.json
  package.json
  sonar-project.properties
  tsconfig.app.json
  vite.config.ts
Labels: ci/cd
